@baseUrl = http://localhost:3001

###
POST {{{{baseUrl}}/public/auth/login
content-type: application/json

{
    "username": "admin",
    "password": "password"
}

###

GET {{{{baseUrl}}/users

###

POST {{baseUrl}}/customers
content-type: application/json

{
    "nadqwdme": "fmeynard customer",
    "toto": "tyolo"
}

###
GET {{baseUrl}}/fadmin/init


###

POST {{baseUrl}}/public/register
Content-Type: application/json

{
    "username": "tosssato {{$guid}}",
    "password": "password",
    "customerName": "test {{$guid}}"
}